headersOrigin = "config"
redirectsOrigin = "config"

[functions]

[functions."*"]

[[plugins]]
origin = "ui"
package = "@netlify/plugin-lighthouse"
pinned_version = "6"

[plugins.inputs]

[build]
publish = "/Users/minishtech/workspace/dohyun/growthwave-admin/dist"
publishOrigin = "config"
commandOrigin = "config"
command = "pnpm build"

[build.environment]
NODE_VERSION = "20"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/assets/*.js"

[headers.values]
Content-Type = "application/javascript; charset=utf-8"

[[headers]]
for = "/assets/*.css"

[headers.values]
Content-Type = "text/css; charset=utf-8"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]