/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedTrashIndexRouteImport } from './routes/_authed/trash/index'
import { Route as AuthedTasksIndexRouteImport } from './routes/_authed/tasks/index'
import { Route as AuthedMarketingTypesIndexRouteImport } from './routes/_authed/marketing-types/index'
import { Route as AuthedExpensesIndexRouteImport } from './routes/_authed/expenses/index'
import { Route as AuthedExpenseCategoriesIndexRouteImport } from './routes/_authed/expense-categories/index'
import { Route as AuthedClientsIndexRouteImport } from './routes/_authed/clients/index'
import { Route as AuthedTasksNewRouteImport } from './routes/_authed/tasks/new'
import { Route as AuthedTasksTaskIdIndexRouteImport } from './routes/_authed/tasks/$taskId/index'
import { Route as AuthedClientsClientIdIndexRouteImport } from './routes/_authed/clients/$clientId/index'
import { Route as AuthedTasksTaskIdEditRouteImport } from './routes/_authed/tasks/$taskId/edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/_authed.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any).lazy(() =>
  import('./routes/_authed/dashboard.lazy').then((d) => d.Route),
)
const AuthedTrashIndexRoute = AuthedTrashIndexRouteImport.update({
  id: '/trash/',
  path: '/trash/',
  getParentRoute: () => AuthedRoute,
} as any).lazy(() =>
  import('./routes/_authed/trash/index.lazy').then((d) => d.Route),
)
const AuthedTasksIndexRoute = AuthedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthedRoute,
} as any).lazy(() =>
  import('./routes/_authed/tasks/index.lazy').then((d) => d.Route),
)
const AuthedMarketingTypesIndexRoute =
  AuthedMarketingTypesIndexRouteImport.update({
    id: '/marketing-types/',
    path: '/marketing-types/',
    getParentRoute: () => AuthedRoute,
  } as any).lazy(() =>
    import('./routes/_authed/marketing-types/index.lazy').then((d) => d.Route),
  )
const AuthedExpensesIndexRoute = AuthedExpensesIndexRouteImport.update({
  id: '/expenses/',
  path: '/expenses/',
  getParentRoute: () => AuthedRoute,
} as any).lazy(() =>
  import('./routes/_authed/expenses/index.lazy').then((d) => d.Route),
)
const AuthedExpenseCategoriesIndexRoute =
  AuthedExpenseCategoriesIndexRouteImport.update({
    id: '/expense-categories/',
    path: '/expense-categories/',
    getParentRoute: () => AuthedRoute,
  } as any).lazy(() =>
    import('./routes/_authed/expense-categories/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthedClientsIndexRoute = AuthedClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AuthedRoute,
} as any).lazy(() =>
  import('./routes/_authed/clients/index.lazy').then((d) => d.Route),
)
const AuthedTasksNewRoute = AuthedTasksNewRouteImport.update({
  id: '/tasks/new',
  path: '/tasks/new',
  getParentRoute: () => AuthedRoute,
} as any).lazy(() =>
  import('./routes/_authed/tasks/new.lazy').then((d) => d.Route),
)
const AuthedTasksTaskIdIndexRoute = AuthedTasksTaskIdIndexRouteImport.update({
  id: '/tasks/$taskId/',
  path: '/tasks/$taskId/',
  getParentRoute: () => AuthedRoute,
} as any).lazy(() =>
  import('./routes/_authed/tasks/$taskId/index.lazy').then((d) => d.Route),
)
const AuthedClientsClientIdIndexRoute =
  AuthedClientsClientIdIndexRouteImport.update({
    id: '/clients/$clientId/',
    path: '/clients/$clientId/',
    getParentRoute: () => AuthedRoute,
  } as any).lazy(() =>
    import('./routes/_authed/clients/$clientId/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthedTasksTaskIdEditRoute = AuthedTasksTaskIdEditRouteImport.update({
  id: '/tasks/$taskId/edit',
  path: '/tasks/$taskId/edit',
  getParentRoute: () => AuthedRoute,
} as any).lazy(() =>
  import('./routes/_authed/tasks/$taskId/edit.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/tasks/new': typeof AuthedTasksNewRoute
  '/clients/': typeof AuthedClientsIndexRoute
  '/expense-categories/': typeof AuthedExpenseCategoriesIndexRoute
  '/expenses/': typeof AuthedExpensesIndexRoute
  '/marketing-types/': typeof AuthedMarketingTypesIndexRoute
  '/tasks/': typeof AuthedTasksIndexRoute
  '/trash/': typeof AuthedTrashIndexRoute
  '/tasks/$taskId/edit': typeof AuthedTasksTaskIdEditRoute
  '/clients/$clientId/': typeof AuthedClientsClientIdIndexRoute
  '/tasks/$taskId/': typeof AuthedTasksTaskIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/tasks/new': typeof AuthedTasksNewRoute
  '/clients': typeof AuthedClientsIndexRoute
  '/expense-categories': typeof AuthedExpenseCategoriesIndexRoute
  '/expenses': typeof AuthedExpensesIndexRoute
  '/marketing-types': typeof AuthedMarketingTypesIndexRoute
  '/tasks': typeof AuthedTasksIndexRoute
  '/trash': typeof AuthedTrashIndexRoute
  '/tasks/$taskId/edit': typeof AuthedTasksTaskIdEditRoute
  '/clients/$clientId': typeof AuthedClientsClientIdIndexRoute
  '/tasks/$taskId': typeof AuthedTasksTaskIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/tasks/new': typeof AuthedTasksNewRoute
  '/_authed/clients/': typeof AuthedClientsIndexRoute
  '/_authed/expense-categories/': typeof AuthedExpenseCategoriesIndexRoute
  '/_authed/expenses/': typeof AuthedExpensesIndexRoute
  '/_authed/marketing-types/': typeof AuthedMarketingTypesIndexRoute
  '/_authed/tasks/': typeof AuthedTasksIndexRoute
  '/_authed/trash/': typeof AuthedTrashIndexRoute
  '/_authed/tasks/$taskId/edit': typeof AuthedTasksTaskIdEditRoute
  '/_authed/clients/$clientId/': typeof AuthedClientsClientIdIndexRoute
  '/_authed/tasks/$taskId/': typeof AuthedTasksTaskIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/tasks/new'
    | '/clients/'
    | '/expense-categories/'
    | '/expenses/'
    | '/marketing-types/'
    | '/tasks/'
    | '/trash/'
    | '/tasks/$taskId/edit'
    | '/clients/$clientId/'
    | '/tasks/$taskId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/tasks/new'
    | '/clients'
    | '/expense-categories'
    | '/expenses'
    | '/marketing-types'
    | '/tasks'
    | '/trash'
    | '/tasks/$taskId/edit'
    | '/clients/$clientId'
    | '/tasks/$taskId'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/_authed/dashboard'
    | '/_authed/tasks/new'
    | '/_authed/clients/'
    | '/_authed/expense-categories/'
    | '/_authed/expenses/'
    | '/_authed/marketing-types/'
    | '/_authed/tasks/'
    | '/_authed/trash/'
    | '/_authed/tasks/$taskId/edit'
    | '/_authed/clients/$clientId/'
    | '/_authed/tasks/$taskId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/trash/': {
      id: '/_authed/trash/'
      path: '/trash'
      fullPath: '/trash/'
      preLoaderRoute: typeof AuthedTrashIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/tasks/': {
      id: '/_authed/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthedTasksIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/marketing-types/': {
      id: '/_authed/marketing-types/'
      path: '/marketing-types'
      fullPath: '/marketing-types/'
      preLoaderRoute: typeof AuthedMarketingTypesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/expenses/': {
      id: '/_authed/expenses/'
      path: '/expenses'
      fullPath: '/expenses/'
      preLoaderRoute: typeof AuthedExpensesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/expense-categories/': {
      id: '/_authed/expense-categories/'
      path: '/expense-categories'
      fullPath: '/expense-categories/'
      preLoaderRoute: typeof AuthedExpenseCategoriesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/clients/': {
      id: '/_authed/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthedClientsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/tasks/new': {
      id: '/_authed/tasks/new'
      path: '/tasks/new'
      fullPath: '/tasks/new'
      preLoaderRoute: typeof AuthedTasksNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/tasks/$taskId/': {
      id: '/_authed/tasks/$taskId/'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId/'
      preLoaderRoute: typeof AuthedTasksTaskIdIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/clients/$clientId/': {
      id: '/_authed/clients/$clientId/'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId/'
      preLoaderRoute: typeof AuthedClientsClientIdIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/tasks/$taskId/edit': {
      id: '/_authed/tasks/$taskId/edit'
      path: '/tasks/$taskId/edit'
      fullPath: '/tasks/$taskId/edit'
      preLoaderRoute: typeof AuthedTasksTaskIdEditRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedTasksNewRoute: typeof AuthedTasksNewRoute
  AuthedClientsIndexRoute: typeof AuthedClientsIndexRoute
  AuthedExpenseCategoriesIndexRoute: typeof AuthedExpenseCategoriesIndexRoute
  AuthedExpensesIndexRoute: typeof AuthedExpensesIndexRoute
  AuthedMarketingTypesIndexRoute: typeof AuthedMarketingTypesIndexRoute
  AuthedTasksIndexRoute: typeof AuthedTasksIndexRoute
  AuthedTrashIndexRoute: typeof AuthedTrashIndexRoute
  AuthedTasksTaskIdEditRoute: typeof AuthedTasksTaskIdEditRoute
  AuthedClientsClientIdIndexRoute: typeof AuthedClientsClientIdIndexRoute
  AuthedTasksTaskIdIndexRoute: typeof AuthedTasksTaskIdIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedTasksNewRoute: AuthedTasksNewRoute,
  AuthedClientsIndexRoute: AuthedClientsIndexRoute,
  AuthedExpenseCategoriesIndexRoute: AuthedExpenseCategoriesIndexRoute,
  AuthedExpensesIndexRoute: AuthedExpensesIndexRoute,
  AuthedMarketingTypesIndexRoute: AuthedMarketingTypesIndexRoute,
  AuthedTasksIndexRoute: AuthedTasksIndexRoute,
  AuthedTrashIndexRoute: AuthedTrashIndexRoute,
  AuthedTasksTaskIdEditRoute: AuthedTasksTaskIdEditRoute,
  AuthedClientsClientIdIndexRoute: AuthedClientsClientIdIndexRoute,
  AuthedTasksTaskIdIndexRoute: AuthedTasksTaskIdIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
